const ORDER_STATUS = {
  RECEIVED: 'RECEIVED',
  PROCESSING: 'PROCESSING',
  READY: 'READY',
  DELIVERED: 'DELIVERED',
};

const VALID_STATUS_TRANSITIONS = {
  [ORDER_STATUS.RECEIVED]: [ORDER_STATUS.PROCESSING],
  [ORDER_STATUS.PROCESSING]: [ORDER_STATUS.READY],
  [ORDER_STATUS.READY]: [ORDER_STATUS.DELIVERED],
  [ORDER_STATUS.DELIVERED]: [],
};

const GARMENT_PRICES = {
  'Shirt': 10,
  'Pants': 15,
  'Saree': 50,
  'Suit': 100,
};

module.exports = {
  ORDER_STATUS,
  VALID_STATUS_TRANSITIONS,
  GARMENT_PRICES,
};
